Commit Final Despliegue

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -14,185 +14,185 @@ env:
   NOMBRE_IMAGEN: laboratorio-final-devsecops
 
 jobs:
-#  SAST:
-#    runs-on: ubuntu-24.04
-#    steps:
-#      # 0. Checkout: Obtenemos el código fuente
-#      - name: Checkout Código
-#        uses: actions/checkout@v3
-#
-#      # 1. Setear la rama como variable de entorno
-#      - name: Configurar Variables de Entorno
-#        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
-#
-#      # 2. Configurar Java 17: Actualización para evitar error de versión de Java
-#      - name: Configurar Java 17
-#        uses: actions/setup-java@v3
-#        with:
-#          java-version: '17'
-#          distribution: 'temurin'  # Puedes elegir otra distribución compatible con Java 17
-#
-#      # 3. Configurar Node.js
-#      - name: Configurar Node.js
-#        uses: actions/setup-node@v3
-#        with:
-#          node-version: 17 # Ajusta según la versión usada en tu proyecto
-#
-#      # 4. Verificar y crear proyecto en SonarCloud si no existe
-#      - name: Verificar y Crear Proyecto en SonarCloud
-#        run: |
-#          # 4. Verificar y crear proyecto en SonarCloud si no existe
-#          echo "Buscando proyecto en SonarCloud..."
-#          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-#            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
-#          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
-#          if [ "$EXISTING_PROJECT" == "1" ]; then
-#            echo "El proyecto ya existe"
-#          else
-#            echo "Creando proyecto en SonarCloud..."
-#            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
-#              "https://sonarcloud.io/api/projects/create" \
-#              -d "name=$REPO_NAME" \
-#              -d "project=$REPO_NAME" \
-#              -d "organization=$ORGANIZACION" \
-#              -d "visibility=public")
-#            if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
-#              echo "Error al crear proyecto en SonarCloud"
-#              #exit 1
-#            else
-#              echo "Proyecto creado exitosamente"
-#            fi
-#          fi
-#
-#      # 5. Instalar SonarScanner
-#      - name: Instalar SonarScanner
-#        run: npm install sonar-scanner --save-dev
-#
-#      # 6. Primer análisis (si el proyecto fue creado)
-#      - name: Realizar Análisis SAST
-#        run: |
-#          # 6. Primer análisis (si el proyecto fue creado)
-#          ./node_modules/.bin/sonar-scanner \
-#            -Dsonar.projectKey=$REPO_NAME \
-#            -Dsonar.organization=$ORGANIZACION \
-#            -Dsonar.host.url=https://sonarcloud.io \
-#            -Dsonar.token=$SONAR_TOKEN \
-#            -Dsonar.branch.name=master \
-#            -Dsonar.exclusions=**/node_modules/**,**/*.flow,**/*.cjs.js.flow
-#
-#      # 7. Validar Quality Gate y vulnerabilidades.
-#      - name: Validar Quality Gate y vulnerabilidades
-#        run: |
-#          #7. Validar Quality Gate y vulnerabilidades.
-#          #OBTENER EL ID DEL ANALISIS REALIZADO
-#          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
-#            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
-#          echo "ID del analisis realizado : $analysisId"
-#
-#          #qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
-#          #  "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
-#          #if [ "$qualityGateStatus" != "OK" ]; then
-#          #  echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus"
-#          #fi
-#
-#          #BUSCA EL STATUS DEL PROYECTO LUEGO DEL ULTIMO ANALISIS REALIZADO
-#          project_status=$(curl -s -u "$SONAR_TOKEN:" \
-#            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.status')
-#          if [ "$project_status" != "SUCCESS" ]; then
-#            echo "El estado del proyecto: $project_status"
-#            #exit 1
-#          else
-#            echo "El estado del proyecto: $project_status"
-#          fi
-#
-#          # BUSCA VULNERABILIDADES CRÍTICAS, ALTAS O MEDIAS EN EL ULTIMO ANALISIS REALIZADO.
-#          echo "Buscando vulnerabilidades del analisis realizado..."
-#          vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
-#            "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" | jq -r '.total')
-#          if [ "$vulnerabilities" -gt 0 ]; then
-#            echo "Se encontraron $vulnerabilities vulnerabilidades críticas, altas o medias. Deteniendo pipeline."
-#            #exit 1
-#          fi
-#          echo "El proyecto no tiene vulnerabilidades críticas, altas o medias."
-#
-#  SCA:
-#    runs-on: ubuntu-24.04
-#    needs: SAST
-#
-#    env:
-#      VULNERABILIDADES: false  # Inicializa la variable de estado.
-#
-#    steps:
-#      # 0. Checkout: Obtenemos el código fuente.
-#      - name: Checkout Código
-#        uses: actions/checkout@v3
-#
-#      # 1. Configurar Node.js con la versión 17
-#      - name: Configurar Node.js
-#        uses: actions/setup-node@v3
-#        with:
-#          node-version: '17'
-#
-#      # 2. Verificar versión de Node.js
-#      - name: Verificar Versión de Node.js
-#        run: node -v
-#
-#      # 3. Instalar dependencias
-#      - name: Instalar Dependencias
-#        run: npm install --legacy-peer-deps
-#
-#      # 4. Crear directorio de reportes
-#      - name: Crear Directorio de Reportes
-#        run: mkdir -p ./reports
-#
-#      # 5. Chequear dependencias usando Snyk
-#      - name: Chequear Dependencias
-#        uses: snyk/actions/node@master
-#        #continua aunque encuentre errores
-#        continue-on-error: true
-#        with:
-#          command: test
-#          args: --severity-threshold=high --json-file-output=./reports/snyk_report.json
-#
-#      # 6. Ejecutar npm audit
-#      - name: Ejecutar npm audit
-#        run: |
-#          npm audit --json > ./reports/npm_audit_report.json || true
-#          if [ $? -ne 0 ]; then
-#            echo "VULNERABILIDADES=true" >> $GITHUB_ENV
-#          fi
-#
-#      # 7. Subir reporte de Snyk
-#      - name: Subir Reporte de Snyk
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: Snyk Report
-#          path: ./reports/snyk_report.json
-#
-#      # 8. Subir reporte de npm audit
-#      - name: Subir Reporte de npm Audit
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: npm Audit Report
-#          path: ./reports/npm_audit_report.json
-#
-#      # 9. Verificar vulnerabilidades de alta severidad
-#      - name: Verificar Vulnerabilidades de Alta Severidad
-#        run: |
-#          if grep -q '"severity": "high"' ./reports/snyk_report.json; then
-#            echo "VULNERABILIDADES=true" >> $GITHUB_ENV
-#          fi
-#      # 10. Fallar si hay vulnerabilidades.
-#      - name: Fallar si hay Vulnerabilidades
-#        run: |
-#          if [ "$VULNERABILIDADES" = "true" ]; then
-#            echo "Vulnerabilidades Detectadas. Detiene proceso de pipeline."
-#            #exit 1
-#          fi
+  SAST:
+    runs-on: ubuntu-24.04
+    steps:
+      # 0. Checkout: Obtenemos el código fuente
+      - name: Checkout Código
+        uses: actions/checkout@v3
+
+      # 1. Setear la rama como variable de entorno
+      - name: Configurar Variables de Entorno
+        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
+
+      # 2. Configurar Java 17: Actualización para evitar error de versión de Java
+      - name: Configurar Java 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'  # Puedes elegir otra distribución compatible con Java 17
+
+      # 3. Configurar Node.js
+      - name: Configurar Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 17 # Ajusta según la versión usada en tu proyecto
+
+      # 4. Verificar y crear proyecto en SonarCloud si no existe
+      - name: Verificar y Crear Proyecto en SonarCloud
+        run: |
+          # 4. Verificar y crear proyecto en SonarCloud si no existe
+          echo "Buscando proyecto en SonarCloud..."
+          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
+          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
+          if [ "$EXISTING_PROJECT" == "1" ]; then
+            echo "El proyecto ya existe"
+          else
+            echo "Creando proyecto en SonarCloud..."
+            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+              "https://sonarcloud.io/api/projects/create" \
+              -d "name=$REPO_NAME" \
+              -d "project=$REPO_NAME" \
+              -d "organization=$ORGANIZACION" \
+              -d "visibility=public")
+            if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
+              echo "Error al crear proyecto en SonarCloud"
+              #exit 1
+            else
+              echo "Proyecto creado exitosamente"
+            fi
+          fi
+
+      # 5. Instalar SonarScanner
+      - name: Instalar SonarScanner
+        run: npm install sonar-scanner --save-dev
+
+      # 6. Primer análisis (si el proyecto fue creado)
+      - name: Realizar Análisis SAST
+        run: |
+          # 6. Primer análisis (si el proyecto fue creado)
+          ./node_modules/.bin/sonar-scanner \
+            -Dsonar.projectKey=$REPO_NAME \
+            -Dsonar.organization=$ORGANIZACION \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.token=$SONAR_TOKEN \
+            -Dsonar.branch.name=master \
+            -Dsonar.exclusions=**/node_modules/**,**/*.flow,**/*.cjs.js.flow
+
+      # 7. Validar Quality Gate y vulnerabilidades.
+      - name: Validar Quality Gate y vulnerabilidades
+        run: |
+          #7. Validar Quality Gate y vulnerabilidades.
+          #OBTENER EL ID DEL ANALISIS REALIZADO
+          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
+          echo "ID del analisis realizado : $analysisId"
+
+          #qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
+          #  "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
+          #if [ "$qualityGateStatus" != "OK" ]; then
+          #  echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus"
+          #fi
+
+          #BUSCA EL STATUS DEL PROYECTO LUEGO DEL ULTIMO ANALISIS REALIZADO
+          project_status=$(curl -s -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.status')
+          if [ "$project_status" != "SUCCESS" ]; then
+            echo "El estado del proyecto: $project_status"
+            #exit 1
+          else
+            echo "El estado del proyecto: $project_status"
+          fi
+
+          # BUSCA VULNERABILIDADES CRÍTICAS, ALTAS O MEDIAS EN EL ULTIMO ANALISIS REALIZADO.
+          echo "Buscando vulnerabilidades del analisis realizado..."
+          vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" | jq -r '.total')
+          if [ "$vulnerabilities" -gt 0 ]; then
+            echo "Se encontraron $vulnerabilities vulnerabilidades críticas, altas o medias. Deteniendo pipeline."
+            #exit 1
+          fi
+          echo "El proyecto no tiene vulnerabilidades críticas, altas o medias."
+
+  SCA:
+    runs-on: ubuntu-24.04
+    needs: SAST
+
+    env:
+      VULNERABILIDADES: false  # Inicializa la variable de estado.
+
+    steps:
+      # 0. Checkout: Obtenemos el código fuente.
+      - name: Checkout Código
+        uses: actions/checkout@v3
+
+      # 1. Configurar Node.js con la versión 17
+      - name: Configurar Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '17'
+
+      # 2. Verificar versión de Node.js
+      - name: Verificar Versión de Node.js
+        run: node -v
+
+      # 3. Instalar dependencias
+      - name: Instalar Dependencias
+        run: npm install --legacy-peer-deps
+
+      # 4. Crear directorio de reportes
+      - name: Crear Directorio de Reportes
+        run: mkdir -p ./reports
+
+      # 5. Chequear dependencias usando Snyk
+      - name: Chequear Dependencias
+        uses: snyk/actions/node@master
+        #continua aunque encuentre errores
+        continue-on-error: true
+        with:
+          command: test
+          args: --severity-threshold=high --json-file-output=./reports/snyk_report.json
+
+      # 6. Ejecutar npm audit
+      - name: Ejecutar npm audit
+        run: |
+          npm audit --json > ./reports/npm_audit_report.json || true
+          if [ $? -ne 0 ]; then
+            echo "VULNERABILIDADES=true" >> $GITHUB_ENV
+          fi
+
+      # 7. Subir reporte de Snyk
+      - name: Subir Reporte de Snyk
+        uses: actions/upload-artifact@v4
+        with:
+          name: Snyk Report
+          path: ./reports/snyk_report.json
+
+      # 8. Subir reporte de npm audit
+      - name: Subir Reporte de npm Audit
+        uses: actions/upload-artifact@v4
+        with:
+          name: npm Audit Report
+          path: ./reports/npm_audit_report.json
+
+      # 9. Verificar vulnerabilidades de alta severidad
+      - name: Verificar Vulnerabilidades de Alta Severidad
+        run: |
+          if grep -q '"severity": "high"' ./reports/snyk_report.json; then
+            echo "VULNERABILIDADES=true" >> $GITHUB_ENV
+          fi
+      # 10. Fallar si hay vulnerabilidades.
+      - name: Fallar si hay Vulnerabilidades
+        run: |
+          if [ "$VULNERABILIDADES" = "true" ]; then
+            echo "Vulnerabilidades Detectadas. Detiene proceso de pipeline."
+            #exit 1
+          fi
 
   Contruir-Docker:
     runs-on: ubuntu-24.04
-    #needs: SCA
+    needs: SCA
     steps:
     # Paso 0: Descargar el código del repositorio
     - name: Checkout Código
@@ -299,18 +299,4 @@ jobs:
         run: |
           docker pull efelantevolador/laboratorio-final-devsecops:latest
           docker run -d --name devsecops-container -p 3000:3000 efelantevolador/laboratorio-final-devsecops:latest
-
-      - name: Verificar contenedores en ejecución
-        id: check_running_containers
-        shell: pwsh
-        run: |
-          docker ps > running_containers.txt
-          if ((Get-Content running_containers.txt).Length -gt 1) {
-              Write-Host "Hay contenedores en ejecución:"
-              Get-Content running_containers.txt
-              echo "containers_running=true" >> $GITHUB_ENV
-          } else {
-              Write-Host "No hay contenedores en ejecución."
-              echo "containers_running=false" >> $GITHUB_ENV
-          }
         
