Docker

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -269,8 +269,15 @@ jobs:
       # Paso 2: Instalar Trivy
       - name: Instalar Trivy
         run: |
+          echo "Instalando Trivy"
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
-          sudo mv trivy /usr/local/bin/
+          if [ -f "./trivy" ]; then
+            sudo mv trivy /usr/local/bin/
+            sudo chmod +x /usr/local/bin/trivy
+          else
+            echo "Error: Trivy no se descargó correctamente"
+            exit 1
+          fi
 
       # Paso 3: Escanear la imagen Docker con Trivy
       - name: Ejecutar Trivy Scan
