creacion de proyecto en SonarCloud correcion 0.0.7

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -1,39 +1,47 @@
 name: Pipeline CI/CD
+
 on:
   push:
     branches:
       - feature-1
+
 # DEFINIMOS VARIABLES DE ENTORNO
 env:
-  REPO_NAME: DevSecOps-Laboratorio
+  REPO_NAME: DevSecOps-Laboratorio-Final
   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   organizacion: devsecops-laboratoriofinal
 
 jobs:
   SAST:
     runs-on: ubuntu-24.04
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+
       # 1. Instalar jq
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
+
       # 2. Configurar Node.js
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 17 # Ajusta según la versión usada en tu proyecto
+
       # 3. Instalar dependencias del proyecto
       - name: Install Dependencies
         run: npm install
+
       # 4. Verificar y crear proyecto en SonarCloud si no existe
       - name: Check and Create Project on SonarCloud
         id: validateProjectOnSonar
         run: |
           echo "Buscando proyecto en SonarCloud..."
+          
           # Buscar el proyecto en SonarCloud
           RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-          "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")
+            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$organizacion")
 
           echo "Response: $RESPONSE"
 
@@ -41,26 +49,14 @@ jobs:
           EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
 
           if [ "$EXISTING_PROJECT" == "null" ]; then
-            echo "Error al obtener datos de la API de SonarCloud." >&2
-            echo "Puede que no exista el proyecto. Intentando crear Proyecto..."
-            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+            echo "Error al obtener datos de la API de SonarCloud."
+            exit 1
+          else
+            # Intentar crear el proyecto en SonarCloud
+            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' \
               "https://sonarcloud.io/api/projects/create" \
               -d "name=$REPO_NAME" \
               -d "project=$REPO_NAME" \
-              -d "organization=$organizacion" \
+              -d "organization=devsecopsusachtest" \
               -d "visibility=public"
-
-            echo "Respuesta: $?"
-
-            if [ $? -eq 0 ]; then
-              echo "Proyecto creado exitosamente en SonarCloud."
-              echo "project_created=true" >> $GITHUB_ENV
-            else
-              echo "Error al intentar crear el proyecto en SonarCloud." >&2
-              exit 1
-            fi
-          else
-            echo "El proyecto ya existe en SonarCloud."
           fi
-
-     
