SAST y SCA

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -12,88 +12,87 @@ env:
   ORGANIZACION: devsecops-laboratoriofinal
 
 jobs:
-  SAST:
-    runs-on: ubuntu-24.04
-
-    steps:
-      #0. Checkout
-      - name: Checkout Code
-        uses: actions/checkout@v3
-      #1. SETEAR LA RAMA COMO VARIABLE DE ENTORNO
-      - name: Set Environment Variables
-        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
-      # 2. Configurar Java 17 (actualización para evitar error de versión de Java)
-      - name: Setup Java 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'temurin'  # Puedes elegir otra distribución compatible con Java 17
-      # 3. Configurar Node.js
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 17 # Ajusta según la versión usada en tu proyecto
-      # 4. Verificar y crear proyecto en SonarCloud si no existe
-      - name: Check and Create Project on SonarCloud
-        #id: validateProjectOnSonar
-        run: |
-          echo "Buscando proyecto en SonarCloud..."
-          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
-          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
-          if [ "$EXISTING_PROJECT" == "1" ]; then
-            echo "El proyecto ya existe"
-            #echo "project_created=true" >> $GITHUB_ENV
-          else
-            echo "Creando proyecto en SonarCloud..."
-            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
-              "https://sonarcloud.io/api/projects/create" \
-              -d "name=$REPO_NAME" \
-              -d "project=$REPO_NAME" \
-              -d "organization=$ORGANIZACION" \
-              -d "visibility=public")
-            if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
-              echo "Error al crear proyecto en SonarCloud"
-              exit 1
-            else
-              echo "Proyecto creado exitosamente"
-              #echo "project_created=true" >> $GITHUB_ENV
-            fi
-          fi
-      # 5. Instalar SonarScanner
-      - name: Install SonarScanner
-        run: |
-          npm install sonar-scanner --save-dev
-      # 6. Primer análisis (si el proyecto fue creado)
-      - name: Perform Initial Analysis on Main
-        #if: env.project_created == 'true'
-        run: |
-          ./node_modules/.bin/sonar-scanner \
-            -Dsonar.projectKey=$REPO_NAME \
-            -Dsonar.organization=$ORGANIZACION \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.token=$SONAR_TOKEN \
-            -Dsonar.branch.name=master \
-            #-Dsonar.exclusions=**/node_modules/**,**/*.flow
-      # 7. Validar Quality Gate
-      - name: Validate Quality Gate
-        run: |
-          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
-            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
-          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
-            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
-          if [ "$qualityGateStatus" != "OK" ]; then
-            echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus"
-            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
-              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
-            if [ "$vulnerabilities" -gt 0 ]; then
-              echo "Se encontraron $vulnerabilities vulnerabilidades críticas. Deteniendo pipeline."
-              exit 1
-            fi
-          else
-            echo "El proyecto cumple con el Quality Gate."
-          fi
-          echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
+  #SAST:
+  #  runs-on: ubuntu-24.04
+  #  steps:
+  #    #0. Checkout
+  #    - name: Checkout Code
+  #      uses: actions/checkout@v3
+  #    #1. SETEAR LA RAMA COMO VARIABLE DE ENTORNO
+  #    - name: Set Environment Variables
+  #      run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
+  #    # 2. Configurar Java 17 (actualización para evitar error de versión de Java)
+  #    - name: Setup Java 17
+  #      uses: actions/setup-java@v3
+  #      with:
+  #        java-version: '17'
+  #        distribution: 'temurin'  # Puedes elegir otra distribución compatible con Java 17
+  #    # 3. Configurar Node.js
+  #    - name: Set up Node.js
+  #      uses: actions/setup-node@v3
+  #      with:
+  #        node-version: 17 # Ajusta según la versión usada en tu proyecto
+  #    # 4. Verificar y crear proyecto en SonarCloud si no existe
+  #    - name: Check and Create Project on SonarCloud
+  #      #id: validateProjectOnSonar
+  #      run: |
+  #        echo "Buscando proyecto en SonarCloud..."
+  #        RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+  #          "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
+  #        EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
+  #        if [ "$EXISTING_PROJECT" == "1" ]; then
+  #          echo "El proyecto ya existe"
+  #          #echo "project_created=true" >> $GITHUB_ENV
+  #        else
+  #          echo "Creando proyecto en SonarCloud..."
+  #          CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+  #            "https://sonarcloud.io/api/projects/create" \
+  #            -d "name=$REPO_NAME" \
+  #            -d "project=$REPO_NAME" \
+  #            -d "organization=$ORGANIZACION" \
+  #            -d "visibility=public")
+  #          if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
+  #            echo "Error al crear proyecto en SonarCloud"
+  #            exit 1
+  #          else
+  #            echo "Proyecto creado exitosamente"
+  #            #echo "project_created=true" >> $GITHUB_ENV
+  #          fi
+  #        fi
+  #    # 5. Instalar SonarScanner
+  #    - name: Install SonarScanner
+  #      run: |
+  #        npm install sonar-scanner --save-dev
+  #    # 6. Primer análisis (si el proyecto fue creado)
+  #    - name: Perform Initial Analysis on Main
+  #      #if: env.project_created == 'true'
+  #      run: |
+  #        ./node_modules/.bin/sonar-scanner \
+  #          -Dsonar.projectKey=$REPO_NAME \
+  #          -Dsonar.organization=$ORGANIZACION \
+  #          -Dsonar.host.url=https://sonarcloud.io \
+  #          -Dsonar.token=$SONAR_TOKEN \
+  #          -Dsonar.branch.name=master \
+  #          #-Dsonar.exclusions=**/node_modules/**,**/*.flow
+  #    # 7. Validar Quality Gate
+  #    - name: Validate Quality Gate
+  #      run: |
+  #        analysisId=$(curl -s -u "$SONAR_TOKEN:" \
+  #          "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
+  #        qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
+  #          "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
+  #        if [ "$qualityGateStatus" != "OK" ]; then
+  #          echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus"
+  #          vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
+  #            "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
+  #          if [ "$vulnerabilities" -gt 0 ]; then
+  #            echo "Se encontraron $vulnerabilities vulnerabilidades críticas. Deteniendo pipeline."
+  #            exit 1
+  #          fi
+  #        else
+  #          echo "El proyecto cumple con el Quality Gate."
+  #        fi
+  #        echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
 
   SCA:
     needs: SAST
