SATS y SCA

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -5,120 +5,119 @@ on:
     branches:
       - feature-1
 
-# DEFINIMOS VARIABLES DE ENTORNO
+# Variables de Entorno
 env:
   REPO_NAME: DevSecOps-Laboratorio-Final
   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   ORGANIZACION: devsecops-laboratoriofinal
+  SONAR_URL: https://sonarcloud.io
+  NPM_AUDIT_REPORT: ./reports/npm_audit_report.json
+  SNYK_REPORT: ./reports/snyk_report.json
 
 jobs:
   SAST:
     runs-on: ubuntu-24.04
+
     steps:
-      #0. Checkout
+      # 0. Checkout: Obtenemos el código fuente
       - name: Checkout Code
         uses: actions/checkout@v3
-      #1. SETEAR LA RAMA COMO VARIABLE DE ENTORNO
+
+      # 1. Set Environment Variables: Define la rama como variable de entorno
       - name: Set Environment Variables
         run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
-      # 2. Configurar Java 17 (actualización para evitar error de versión de Java)
+
+      # 2. Setup Java 17: Configura Java 17 para evitar errores de versión
       - name: Setup Java 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
-          distribution: 'temurin'  # Puedes elegir otra distribución compatible con Java 17
-      # 3. Configurar Node.js
+          distribution: 'temurin'
+
+      # 3. Setup Node.js: Configura Node.js con la versión 17
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 17 # Ajusta según la versión usada en tu proyecto
-      # 4. Verificar y crear proyecto en SonarCloud si no existe
+          node-version: 17
+
+      # 4. Check and Create Project on SonarCloud: Verifica y crea proyecto en SonarCloud si no existe
       - name: Check and Create Project on SonarCloud
-        #id: validateProjectOnSonar
         run: |
           echo "Buscando proyecto en SonarCloud..."
-          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
-          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
+          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "$SONAR_URL/api/projects/search?projects=$REPO_NAME&organization=$ORGANIZACION")
+          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total')
           if [ "$EXISTING_PROJECT" == "1" ]; then
             echo "El proyecto ya existe"
-            #echo "project_created=true" >> $GITHUB_ENV
           else
             echo "Creando proyecto en SonarCloud..."
-            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
-              "https://sonarcloud.io/api/projects/create" \
-              -d "name=$REPO_NAME" \
-              -d "project=$REPO_NAME" \
-              -d "organization=$ORGANIZACION" \
-              -d "visibility=public")
+            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" "$SONAR_URL/api/projects/create" -d "name=$REPO_NAME" -d "project=$REPO_NAME" -d "organization=$ORGANIZACION" -d "visibility=public")
             if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
               echo "Error al crear proyecto en SonarCloud"
               exit 1
             else
               echo "Proyecto creado exitosamente"
-              #echo "project_created=true" >> $GITHUB_ENV
             fi
           fi
-      # 5. Instalar SonarScanner
+
+      # 5. Install SonarScanner: Instala SonarScanner como dependencia de desarrollo
       - name: Install SonarScanner
-        run: |
-          npm install sonar-scanner --save-dev
-      # 6. Primer análisis (si el proyecto fue creado)
+        run: npm install sonar-scanner --save-dev
+
+      # 6. Perform Initial Analysis on Main: Realiza el primer análisis en la rama master
       - name: Perform Initial Analysis on Main
-        #if: env.project_created == 'true'
         run: |
           ./node_modules/.bin/sonar-scanner \
             -Dsonar.projectKey=$REPO_NAME \
             -Dsonar.organization=$ORGANIZACION \
-            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.host.url=$SONAR_URL \
             -Dsonar.token=$SONAR_TOKEN \
-            -Dsonar.branch.name=master \
-            #-Dsonar.exclusions=**/node_modules/**,**/*.flow
-      # 7. Validar Quality Gate
+            -Dsonar.branch.name=master
+
+      # 7. Validate Quality Gate: Valida el estado del Quality Gate en SonarCloud
       - name: Validate Quality Gate
         run: |
-          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
-            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
-          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
-            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
+          analysisId=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_URL/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
+          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_URL/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
           if [ "$qualityGateStatus" != "OK" ]; then
             echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus"
-            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
-              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
+            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_URL/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
             if [ "$vulnerabilities" -gt 0 ]; then
               echo "Se encontraron $vulnerabilities vulnerabilidades críticas. Deteniendo pipeline."
               exit 1
             fi
           else
             echo "El proyecto cumple con el Quality Gate."
-          fi
-          echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
 
-  
   SCA:
     runs-on: ubuntu-24.04
 
     env:
-        VULNERABILIDADES: false  # Inicializa la variable de estado
+      VULNERABILIDADES: false  # Inicializa la variable de estado
 
     steps:
+      # 0. Checkout: Obtenemos el código fuente
       - name: Checkout code
         uses: actions/checkout@v3
 
+      # 1. Set up Node.js: Configura Node.js con la versión 20
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '20'
 
+      # 2. Check Node.js version: Verifica la versión de Node.js instalada
       - name: Check Node.js version
         run: node -v
 
+      # 3. Install dependencies: Instala las dependencias del proyecto
       - name: Install dependencies
         run: npm install --legacy-peer-deps
 
+      # 4. Create reports directory: Crea un directorio para los reportes
       - name: Create reports directory
         run: mkdir -p ./reports
 
+      # 5. Dependency Check: Ejecuta un chequeo de dependencias usando Snyk
       - name: Dependency Check
         uses: snyk/actions/node@master
         continue-on-error: true
@@ -126,48 +125,38 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: test
-          args: --severity-threshold=high --json-file-output=./reports/snyk_report.json
+          args: --severity-threshold=high --json-file-output=$SNYK_REPORT
 
+      # 6. Run npm audit: Realiza un npm audit y guarda el reporte
       - name: Run npm audit
         run: |
-          npm audit --json > ./reports/npm_audit_report.json || true
+          npm audit --json > $NPM_AUDIT_REPORT || true
           if [ $? -ne 0 ]; then
             echo "VULNERABILIDADES=true" >> $GITHUB_ENV
-          fi
 
+      # 7. Upload Snyk Report: Sube el reporte de Snyk como artefacto
       - name: Upload Snyk Report
         uses: actions/upload-artifact@v4
         with:
           name: Snyk Report
-          path: ./reports/snyk_report.json
+          path: $SNYK_REPORT
 
+      # 8. Upload npm Audit Report: Sube el reporte de npm audit como artefacto
       - name: Upload npm Audit Report
         uses: actions/upload-artifact@v4
         with:
           name: npm Audit Report
-          path: ./reports/npm_audit_report.json
+          path: $NPM_AUDIT_REPORT
 
+      # 9. Check for high severity vulnerabilities: Verifica si hay vulnerabilidades de alta severidad
       - name: Check for high severity vulnerabilities
         run: |
-          if grep -q '"severity": "high"' ./reports/snyk_report.json; then
+          if grep -q '"severity": "high"' $SNYK_REPORT; then
             echo "VULNERABILIDADES=true" >> $GITHUB_ENV
-          fi
 
-      # Paso adicional para detener el pipeline si hay vulnerabilidades
+      # 10. Fail if there are vulnerabilities: Detiene el pipeline si se detectan vulnerabilidades de alta severidad
       - name: Fail if there are vulnerabilities
         run: |
           if [ "$VULNERABILIDADES" = "true" ]; then
             echo "Vulnerabilidades Detectadas. Detiene proceso de pipeline."
-            #exit 1
-          fi
-
-
-
-
-
-
-
-
-
-
-
+            exit 1
