creacion de proyecto en SonarCloud Correccion Creacion proyecto V 0.1.3

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -48,27 +48,25 @@ jobs:
           # Verificar si la respuesta contiene datos válidos
           EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)
 
-          if [ "$EXISTING_PROJECT" == "null" ]; then
+          if [ "$EXISTING_PROJECT" == "1" ]; then
+            echo "El proyecto ya existe"
+          elif [ "$EXISTING_PROJECT" == "null" ]; then
             echo "Error al obtener datos de la API de SonarCloud."
             exit 1
           else
-            echo "Proyecto no exite..."
-            echo "Creando proyecto en SonarCloud..."
-            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' \
+            echo "Proyecto no existe... Creando proyecto en SonarCloud..."
+            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
               "https://sonarcloud.io/api/projects/create" \
               -d "name=$REPO_NAME" \
               -d "project=$REPO_NAME" \
               -d "organization=$organizacion" \
-              -d "visibility=public"
-              
-              # Verificar si la respuesta contiene datos válidos
-              CREACION_PROJECT=$(echo "$?" | jq '.paging.total' 2>/dev/null)
-
-              if [ $? -ne 0 ]; then
-                echo "Proyecto ${{ github.event.repository.name }} / $REPO_NAME creado exitosamente en SonarCloud"
-              else
-                echo "Fallo la creacion"
-                exit 1
-              fi
-
+              -d "visibility=public")
+            
+            # Verificar si la creación fue exitosa
+            if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
+              echo "Fallo la creación del proyecto en SonarCloud"
+              exit 1
+            else
+              echo "Proyecto $REPO_NAME creado exitosamente en SonarCloud"
+            fi
           fi
